 version: '4'
 services:
   mongodb:
     image: mongo:7.0.5
     container_name: mongodb
     ports:
       - "27017:27017"
     environment:
       MONGO_INTIDB_ROOT_USERNAME: root
       MONGO_INTIDB_ROOT_PASSWORD: password
       MONGO_INTIDB_DATABASE: product-service
     volumes:
       - ./data:/data/db